3   CLASS
4   NUMBER OPERATOR
6   NUMBER OPERATOR
7   FUNCTION_USE OPERATOR CLASS_VAR
8   CLASS_VAR
9   BOOLEAN OPERATOR
10  NUMBER NUMBER OPERATOR
13  FUNCTION_USE OPERATOR CLASS_VAR
15  FUNCTION_USE
16  FUNCTION_USE OPERATOR
17  OPERATOR
18  FUNCTION_USE OPERATOR OPERATOR
19  IF_OR_ELSE
20  FUNCTION_USE
22  FUNCTION_USE
22  FUNCTION_USE
22  FUNCTION_USE
25  FUNCTION_DEF VOID
26  IF_OR_ELSE
27  OPERATOR
28  IF_OR_ELSE
29  OPERATOR
31  IF_OR_ELSE
33  OPERATOR
35  IF_OR_ELSE
36  OPERATOR
38  IF_OR_ELSE
39  OPERATOR
41  LOOP
43  FUNCTION_USE
44  OPERATOR
45  LOOP
48  TRY
49  IF_OR_ELSE
50  IF_OR_ELSE
51  OPERATOR
52  CATCH
53  FUNCTION_USE
57  FUNCTION_DEF VOID
58  FUNCTION_USE
60  FUNCTION_USE TEXT OPERATOR
62  TEXT OPERATOR
63  TEXT OPERATOR
64  BYTE OPERATOR
66  FUNCTION_USE
68  OPERATOR CLASS_VAR
70  LOOP
71  LOOP
72  OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR
75  IF_OR_ELSE
80  FUNCTION_DEF VOID
82  SWITCH
84  FUNCTION_USE
90  FUNCTION_USE
95  FUNCTION_DEF VOID
98  OPERATOR OPERATOR
99  OPERATOR OPERATOR
100 OPERATOR OPERATOR OPERATOR
101 OPERATOR OPERATOR OPERATOR
102 OPERATOR OPERATOR OPERATOR OPERATOR
103 OPERATOR OPERATOR OPERATOR
104 OPERATOR OPERATOR OPERATOR
105 OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR
106 OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR
107 OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR OPERATOR