3	CLASS EXTENDS IMPLEMENTS
4	STATIC FINAL LONG OP_ASSIGN
6	FINAL INT OP_ASSIGN
7	FUNCTION_USE NEW OP_ASSIGN CLASS_VAR
8	CLASS_VAR
9	BOOLEAN OP_ASSIGN
10	NEW INT INT OP_ASSIGN TABLE TABLE TABLE TABLE
13	FUNCTION_USE NEW OP_ASSIGN CLASS_VAR
15	FUNCTION_USE INT INT CLASS_VAR
16	FUNCTION_USE NEW OP_ASSIGN
17	OP_ASSIGN
18	INT
19	FUNCTION_USE OP_ASSIGN OP_ARITHMETIC
20	IF_OR_ELSE FUNCTION_USE FUNCTION_USE OP_RELATION OP_RELATION OP_LOGIC
21	FUNCTION_USE
23	FUNCTION_USE
23	FUNCTION_USE
23	FUNCTION_USE
26	FUNCTION_DEF THROWS VOID
27	IF_OR_ELSE OP_RELATION
28	OP_ASSIGN
29	IF_OR_ELSE OP_RELATION
30	OP_ASSIGN
32	IF_OR_ELSE
34	OP_ASSIGN
36	IF_OR_ELSE
37	OP_ASSIGN
39	IF_OR_ELSE
40	OP_ASSIGN
42	DO
44	FUNCTION_USE OP_ARITHMETIC
45	OP_ARITHMETIC
46	WHILE OP_RELATION
49	TRY
50	IF_OR_ELSE OP_RELATION
51	IF_OR_ELSE OP_RELATION
52	OP_ARITHMETIC
53	CATCH
54	FUNCTION_USE FUNCTION_USE OP_ARITHMETIC
58	FUNCTION_DEF VOID CLASS_VAR
59	FUNCTION_USE
61	FUNCTION_USE STRING OP_ASSIGN TABLE
63	CHAR OP_ASSIGN
64	STRING OP_ASSIGN
65	BYTE OP_ASSIGN
67	FUNCTION_USE OP_ARITHMETIC OP_ARITHMETIC
69	CAST OP_ASSIGN CLASS_VAR
71	FOR INT OP_RELATION OP_ASSIGN OP_ARITHMETIC
72	FOR INT OP_RELATION OP_ASSIGN OP_ARITHMETIC
73	OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
74	OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
77	IF_OR_ELSE OP_RELATION OP_RELATION OP_RELATION OP_LOGIC OP_LOGIC TABLE TABLE TABLE TABLE TABLE TABLE TABLE TABLE TABLE TABLE
78	RETURN
82	FUNCTION_DEF STATIC VOID STRING TABLE
84	SWITCH
85	CASE
86	FUNCTION_USE
87	BREAK
88	CASE
89	CASE
90	BREAK
91	DEFAULT
92	FUNCTION_USE
97	FUNCTION_DEF VOID CLASS_VAR
100	OP_ARITHMETIC OP_ARITHMETIC
101	OP_ARITHMETIC OP_ARITHMETIC
102	OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
103	OP_BITWISE OP_BITWISE OP_BITWISE
104	OP_RELATION OP_RELATION OP_RELATION OP_RELATION
105	OP_RELATION OP_RELATION OP_LOGIC
106	OP_BITWISE OP_BITWISE OP_BITWISE
107	OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
108	OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_BITWISE OP_BITWISE OP_BITWISE
109	OP_BITWISE OP_BITWISE OP_BITWISE OP_ASSIGN OP_ASSIGN OP_ASSIGN