3   CLASS EXTENDS IMPLEMENTS
4   STATIC FINAL NUMBER_WHOLE OP_ASSIGN
6   FINAL NUMBER_WHOLE OP_ASSIGN
7   FUNCTION_USE NEW OP_ASSIGN CLASS_VAR
8   CLASS_VAR
9   BOOLEAN OP_ASSIGN
10  NEW NUMBER_WHOLE NUMBER_WHOLE OP_ASSIGN TABLE TABLE TABLE TABLE
13  FUNCTION_USE NEW OP_ASSIGN CLASS_VAR
15  FUNCTION_USE
16  FUNCTION_USE NEW OP_ASSIGN
17  OP_ASSIGN
18  FUNCTION_USE OP_ASSIGN OP_ARITHMETIC
19  IF_OR_ELSE
20  FUNCTION_USE
22  FUNCTION_USE
22  FUNCTION_USE
22  FUNCTION_USE
25  FUNCTION_DEF THROWS VOID
26  IF_OR_ELSE
27  OP_ASSIGN
28  IF_OR_ELSE
29  OP_ASSIGN
31  IF_OR_ELSE
33  OP_ASSIGN
35  IF_OR_ELSE
36  OP_ASSIGN
38  IF_OR_ELSE
39  OP_ASSIGN
41  LOOP
43  FUNCTION_USE
44  OP_ARITHMETIC
45  LOOP
48  TRY
49  IF_OR_ELSE
50  IF_OR_ELSE
51  OP_ARITHMETIC
52  CATCH
53  FUNCTION_USE
57  FUNCTION_DEF VOID
58  FUNCTION_USE
60  FUNCTION_USE TEXT OP_ASSIGN TABLE
62  TEXT OP_ASSIGN
63  TEXT OP_ASSIGN
64  BYTE OP_ASSIGN
66  FUNCTION_USE
68  CAST OP_ASSIGN CLASS_VAR
70  LOOP
71  LOOP
72  OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
75  IF_OR_ELSE
76  RETURN
80  FUNCTION_DEF STATIC VOID
82  SWITCH
83  CASE
84  FUNCTION_USE
85  BREAK
86  CASE
87  CASE
88  BREAK
89  DEFAULT
90  FUNCTION_USE
95  FUNCTION_DEF VOID
98  OP_ARITHMETIC OP_ARITHMETIC
99  OP_ARITHMETIC OP_ARITHMETIC
100 OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
101 OP_BITWISE OP_BITWISE OP_BITWISE
102 OP_RELATION OP_RELATION OP_RELATION OP_RELATION
103 OP_RELATION OP_RELATION OP_LOGIC
104 OP_BITWISE OP_BITWISE OP_BITWISE
105 OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_ARITHMETIC
106 OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ASSIGN OP_ARITHMETIC OP_ARITHMETIC OP_BITWISE OP_BITWISE OP_BITWISE
107 OP_BITWISE OP_BITWISE OP_BITWISE OP_ASSIGN OP_ASSIGN OP_ASSIGN